### ISSUE TITLE
Publish package to nuget

### ISSUE THREAD

**Issue by tinohager** [Altaxo/Altaxo#11]
Hi

I like this library if it possible to publish it to nuget? (nuget.org?)
I am use AltaxoCore.dll. The project is not buildable with Visual Studio Community 2017.

Best regards
Tino

**Comment by lellid** [comment]
Sorry, I don't intend to publish AltaxoCore to nuget. This is mainly because I can not guarantee that the list of APIs in AltaxoCore will not change. If fact, I intend to completely revise the LinearAlgebra namespace, in order to support sparse matrices etc.
Building with Visual Studio Community 2017 should work, because I'm using it too. Maybe the conversion of the T4 text templates is the problem?

**Comment by tinohager** [comment]
I think it is no problem when you change the api. You have different version on nuget everbody can install a old version.

Yes the problem is with the T4 Templates in Visual Studio 2017 Community.
